baseURL: /
languageCode: en-us
paginate: 6
theme: portio-hugo-data-science
title: Sudhir's Data Science Portfolio
menu:
  main:
    - name: Home
      url: '#home'
      weight: 1
    - name: About
      url: '#about'
      weight: 2
    - name: Portfolio
      url: '#portfolio'
      weight: 4
    - name: Resume
      url: '#resume'
      weight: 5
    - name: Blog
      url: blog
      weight: 6
  sitemap:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: blog
      weight: 2
params:
  blogPageURL: blog
  contactButtonLabel: Contact Sudhir
  contactLink: '#contact'
  copyright: All right reserved copyright © Sudhir Singh 2023 
  footerLogo: images/site-navigation/logo-sudhir.png
  formspreeURL: https://formspree.io/f/xdovkgyv
  googleAnalytics: YOUR GOOGLE ANALYTICS CODE
  logo: images/site-navigation/logo-sudhir.png
  social:
    - icon: fa-linkedin-square
      url: https://www.linkedin.com/in/sudhirsinghkumar/
      weight: 1
    - icon: fa-twitter-square
      url: https://twitter.com/sudhirparasar
      weight: 2
